# fallback_config.yaml
# Dual-Face Tracker 안전한 기본 설정
# 하드웨어 프로빙 실패시 사용되는 보수적 기본값

# =============================================================================
# 🚨 중요: 이 파일은 하드웨어 프로빙 실패시에만 사용됩니다
# 수동 설정을 원한다면 manual_config.yaml을 생성하세요
# =============================================================================

# 하드웨어 정보 (기본값)
hardware:
  gpu_name: "Unknown GPU"
  nvdec_max_sessions: 2          # 안전한 기본값 (대부분 GPU에서 지원)
  nvenc_max_sessions: 2          # 안전한 기본값
  vram_gb: 8                     # 최소 VRAM 가정
  driver_version: "Unknown"
  cuda_version: "12.x"
  compute_capability: "Unknown"

# 성능 설정 (보수적)
performance:
  max_concurrent_streams: 2      # 보수적 기본값
  batch_size_analyze: 32         # 작은 배치 크기로 안전성 확보
  vram_safety_margin: 0.25       # 25% 안전 마진 (보수적)
  target_gpu_utilization: 0.7    # 70% 목표 (안전한 수준)

# NVDEC 설정
nvdec_settings:
  max_sessions: 2
  preferred_format: "nv12"       # NVDEC 표준 출력 포맷
  hwaccel_device: "cuda"         # 하드웨어 가속 디바이스
  thread_type: "auto"            # 자동 스레딩

# NVENC 설정  
nvenc_settings:
  max_sessions: 2
  preset: "medium"               # 품질과 성능의 균형
  rc_mode: "cbr"                 # Constant Bit Rate
  profile: "high"                # H.264 High Profile
  level: "4.1"                   # 호환성을 위한 안전한 레벨

# 디코딩 설정
decoding:
  output_format: "rgb24"         # RGB 24비트 출력
  interpolation: "bilinear"      # 기본 보간 방법
  seek_threshold: 1.0            # 1초 탐색 임계값
  frame_buffer_size: 10          # 프레임 버퍼 크기

# 인코딩 설정
encoding:
  video_codec: "h264_nvenc"      # NVENC H.264
  audio_codec: "aac"             # AAC 오디오
  bitrate: "5M"                  # 5Mbps 기본 비트레이트
  keyframe_interval: 30          # 30프레임마다 키프레임

# 에러 처리 설정
error_handling:
  max_retries: 3                 # 최대 재시도 횟수
  timeout_seconds: 30            # 작업 타임아웃
  graceful_degradation: true     # 점진적 성능 저하 허용
  fallback_to_cpu: true          # CPU 폴백 허용

# 로깅 설정
logging:
  level: "INFO"                  # 로그 레벨
  file_path: "dual_face_tracker.log"
  max_size_mb: 100               # 최대 로그 파일 크기
  backup_count: 3                # 백업 파일 수
  console_output: true           # 콘솔 출력 여부

# 모니터링 설정
monitoring:
  gpu_memory_check_interval: 10  # GPU 메모리 체크 간격 (프레임)
  performance_report_interval: 100  # 성능 리포트 간격
  enable_profiling: false        # 프로파일링 비활성화 (성능상 이유)

# 메타데이터
metadata:
  config_type: "fallback"
  description: "Safe default configuration for dual-face tracker"
  version: "1.0"
  created_by: "HybridConfigManager"
  creation_timestamp: "auto-generated"
  
# 호환성 설정
compatibility:
  min_cuda_version: "11.0"       # 최소 CUDA 버전
  min_pytorch_version: "2.0.0"   # 최소 PyTorch 버전
  min_pyav_version: "11.0.0"     # 최소 PyAV 버전
  tested_gpu_architectures:      # 테스트된 GPU 아키텍처
    - "Pascal"      # GTX 10xx
    - "Volta"       # V100
    - "Turing"      # RTX 20xx
    - "Ampere"      # RTX 30xx  
    - "Ada Lovelace" # RTX 40xx
    - "Blackwell"   # RTX 50xx

# 개발 설정 (디버그용)
development:
  debug_mode: false
  save_intermediate_frames: false
  enable_memory_profiling: false
  verbose_gpu_logging: false